"use client";

import Link from "next/link";
import { use, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Button } from "@forno/ui/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@forno/ui/components/card";
import { Input } from "@forno/ui/components/input";
import { Label } from "@forno/ui/components/label";
import { useLocale } from "next-intl";
import { toast } from "sonner";
import { InventoryNav, InventoryPageHeader, formatExactQuantity } from "@/components/inventory/inventory-nav";
import { parseDecimalToScaled } from "@/lib/inventory/exact";
import { useTRPC } from "@/lib/trpc/client";

export default function StockCountDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const countId = Number(id); const trpc = useTRPC(); const ar = useLocale() === "ar"; const qc = useQueryClient();
  const inventory = useQuery(trpc.inventory.context.queryOptions()); const branchId = inventory.data?.branch.id ?? 0;
  const context = useQuery(trpc.stockCounts.context.queryOptions()); const detailsOptions = trpc.stockCounts.detail.queryOptions({ branchId, countId }); const detail = useQuery({ ...detailsOptions, enabled: branchId > 0 && Number.isInteger(countId) });
  const locations = useQuery({ ...trpc.stockCounts.locations.queryOptions({ branchId }), enabled: branchId > 0 });
  const ingredientConversions = useQuery({ ...trpc.stockCounts.ingredients.queryOptions({ branchId }), enabled: branchId > 0 && Boolean(context.data?.canEnter) });
  const [values, setValues] = useState<Record<number, { quantity: string; unit: string; zero: boolean }>>({}); const [reason, setReason] = useState(""); const [draftLocationId, setDraftLocationId] = useState(""); const [draftNotes, setDraftNotes] = useState<string | null>(null); const [search, setSearch] = useState("");
  const refresh = async () => Promise.all([qc.invalidateQueries({ queryKey: detailsOptions.queryKey }), qc.invalidateQueries({ queryKey: trpc.stockCounts.list.queryOptions({ branchId }).queryKey }), qc.invalidateQueries({ queryKey: trpc.inventory.overview.queryOptions({ branchId }).queryKey }), qc.invalidateQueries({ queryKey: trpc.inventory.movements.queryOptions({ branchId }).queryKey })]);
  const start = useMutation(trpc.stockCounts.start.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const enter = useMutation(trpc.stockCounts.enterLine.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const editDraft = useMutation(trpc.stockCounts.editDraft.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const submit = useMutation(trpc.stockCounts.submit.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const approve = useMutation(trpc.stockCounts.approve.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const post = useMutation(trpc.stockCounts.post.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const cancel = useMutation(trpc.stockCounts.cancel.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  const reverse = useMutation(trpc.stockCounts.reverse.mutationOptions({ onSuccess: refresh, onError: (error) => toast.error(error.message) }));
  if (!detail.data) return <main className="p-4 sm:p-6"><InventoryNav /><p>{ar ? "جارٍ تحميل الجرد…" : "Loading stock count…"}</p></main>;
  const row = detail.data; const busy = start.isPending || enter.isPending || submit.isPending || approve.isPending || post.isPending || cancel.isPending || reverse.isPending;
  return <main className="p-4 sm:p-6"><InventoryNav /><InventoryPageHeader titleEn={`Stock count ${row.count_number}`} titleAr={`جرد المخزون ${row.count_number}`} descriptionEn={`${row.location_id} · ${row.status.replaceAll("_", " ")} · ${row.lines.filter((line) => line.counted_quantity_base !== null).length}/${row.lines.length} counted`} descriptionAr={`${row.status.replaceAll("_", " ")} · تم عد ${row.lines.filter((line) => line.counted_quantity_base !== null).length} من ${row.lines.length}`} />
    {row.status === "needs_review" && <div role="alert" className="mb-4 rounded-lg border border-destructive p-3 text-destructive">{row.needs_review_reason}</div>}
    {row.status === "draft" && context.data?.canCreate && <Card className="mb-4"><CardHeader><CardTitle>{ar ? "تعديل إعدادات المسودة" : "Edit draft setup"}</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2"><div className="space-y-1"><Label htmlFor="draft-location">{ar ? "الموقع" : "Location"}</Label><select id="draft-location" className="h-11 w-full rounded-md border bg-background px-3" value={draftLocationId || String(row.location_id)} onChange={(event) => setDraftLocationId(event.target.value)}>{locations.data?.map((location) => <option key={location.id} value={location.id}>{ar ? location.name_ar : location.name_en}</option>)}</select></div><div className="space-y-1"><Label htmlFor="draft-notes">{ar ? "ملاحظات" : "Notes"}</Label><Input id="draft-notes" value={draftNotes ?? row.notes ?? ""} onChange={(event) => setDraftNotes(event.target.value)} /></div><Button className="min-h-11 sm:col-span-2" disabled={editDraft.isPending} onClick={() => editDraft.mutate({ branchId, countId, locationId: Number(draftLocationId || row.location_id), notes: draftNotes ?? row.notes })}>{ar ? "حفظ إعدادات المسودة" : "Save draft setup"}</Button></CardContent></Card>}
    <Card><CardHeader><CardTitle>{ar ? "سطور الجرد" : "Count lines"}</CardTitle></CardHeader><CardContent className="space-y-3"><Input aria-label={ar ? "ابحث عن مكون" : "Search ingredients"} placeholder={ar ? "ابحث بالاسم أو الكود" : "Search by ingredient name or code"} value={search} onChange={(event) => setSearch(event.target.value)} />{row.lines.filter((line) => `${line.ingredient_name_en_snapshot} ${line.ingredient_name_ar_snapshot} ${line.ingredient_sku_snapshot}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())).map((line) => {
      const current = values[line.id] ?? { quantity: line.counted_input_scaled === null ? "" : String(line.counted_input_scaled / 1000), unit: line.package_conversion_id ? `p:${line.package_conversion_id}` : `u:${line.counted_unit_id ?? line.base_unit_id}`, zero: line.zero_confirmed };
      const conversions = ingredientConversions.data?.find((item) => item.id === line.ingredient_id)?.packages ?? [];
      return <section key={line.id} className="space-y-3 rounded-lg border p-3 sm:p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{ar ? line.ingredient_name_ar_snapshot : line.ingredient_name_en_snapshot}</h3><p className="text-xs text-muted-foreground">{line.ingredient_sku_snapshot} · {line.base_unit_code_snapshot}</p></div>{line.expected_quantity_base !== null && <span className="text-sm">{ar ? "المتوقع" : "Expected"}: {formatExactQuantity(line.expected_quantity_base, line.dimension_snapshot)}</span>}</div>
        {row.status === "counting" && context.data?.canEnter && <><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(140px,0.8fr)]"><div className="space-y-1"><Label htmlFor={`count-${line.id}`}>{ar ? "الكمية الفعلية" : "Physical quantity"}</Label><Input id={`count-${line.id}`} aria-label={`Physical quantity ${line.ingredient_name_en_snapshot}`} inputMode="decimal" disabled={current.zero} value={current.quantity} onChange={(e) => setValues((old) => ({ ...old, [line.id]: { ...current, quantity: e.target.value } }))} /></div><div className="space-y-1"><Label htmlFor={`unit-${line.id}`}>{ar ? "وحدة العد" : "Count unit"}</Label><select id={`unit-${line.id}`} aria-label={`Count unit ${line.ingredient_name_en_snapshot}`} className="h-11 w-full rounded-md border bg-background px-2" value={current.unit} onChange={(e) => setValues((old) => ({ ...old, [line.id]: { ...current, unit: e.target.value } }))}><option value={`u:${line.base_unit_id}`}>{line.base_unit_code_snapshot} · {ar ? "أساسي" : "Base unit"}</option>{conversions.map((pkg) => <option key={pkg.id} value={`p:${pkg.id}`}>{pkg.code} · {ar ? pkg.name_ar : pkg.name_en} ({pkg.base_numerator}/{pkg.base_denominator})</option>)}</select></div></div><label className="flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" className="h-5 w-5" checked={current.zero} onChange={(e) => setValues((old) => ({ ...old, [line.id]: { ...current, zero: e.target.checked, quantity: e.target.checked ? "0" : "" } }))} />{ar ? "تأكيد أن الكمية صفر" : "Explicitly confirm zero quantity"}</label><Button className="min-h-11" disabled={busy || (!current.zero && !current.quantity.trim())} onClick={() => { let quantityScaled: number | null = null; try { quantityScaled = current.zero ? 0 : parseDecimalToScaled(current.quantity); } catch (error) { toast.error(error instanceof Error ? error.message : "Invalid quantity"); return; } const [kind, raw] = current.unit.split(":"); enter.mutate({ branchId, countId, lineId: line.id, quantityScaled, zeroConfirmed: current.zero, unitId: line.base_unit_id, packageConversionId: kind === "p" ? Number(raw) : null, idempotencyKey: `count-entry:${row.id}:${line.id}:${crypto.randomUUID()}` }); }}>{ar ? "حفظ الكمية" : "Save counted quantity"}</Button></>}
        {line.counted_quantity_base !== null && <p className="text-sm">{ar ? "المعدود" : "Counted"}: {formatExactQuantity(line.counted_quantity_base, line.dimension_snapshot)} {line.zero_confirmed && <span className="text-muted-foreground">· {ar ? "صفر مؤكد" : "Confirmed zero"}</span>}</p>}
        {line.variance_base !== null && <p className="text-sm">{ar ? "الانحراف" : "Variance"}: {formatExactQuantity(line.variance_base, line.dimension_snapshot)}{line.valuation_amount !== null ? ` · ${ar ? "قيمة التعديل" : "Adjustment value"} EGP ${line.valuation_amount}` : ""}</p>}
      </section>;
    })}</CardContent></Card>
    <div className="mt-4 flex flex-wrap items-end gap-2">{context.data?.canStart && row.status === "draft" && <Button className="min-h-11" disabled={busy} onClick={() => start.mutate({ branchId, countId, idempotencyKey: `count-start:${row.id}` })}>{ar ? "بدء العد" : "Start counting"}</Button>}{context.data?.canSubmit && row.status === "counting" && <Button className="min-h-11" disabled={busy} onClick={() => submit.mutate({ branchId, countId, idempotencyKey: `count-submit:${row.id}` })}>{ar ? "إرسال للمراجعة" : "Submit for review"}</Button>}
      {(context.data?.canApprove && row.status === "submitted" || context.data?.canPost && row.status === "approved" || context.data?.canCancel && ["draft", "counting", "submitted", "approved"].includes(row.status) || context.data?.canReverse && row.status === "posted") && <div className="w-full max-w-md space-y-1"><Label htmlFor="action-reason">{ar ? "السبب (للإجراءات الحساسة)" : "Reason (required for sensitive actions)"}</Label><Input id="action-reason" value={reason} onChange={(e) => setReason(e.target.value)} />
      {context.data?.canApprove && row.status === "submitted" && <Button className="min-h-11" disabled={busy || reason.trim().length < 3} onClick={() => approve.mutate({ branchId, countId, reason, idempotencyKey: `count-approve:${row.id}` })}>{ar ? "اعتماد الجرد" : "Approve count"}</Button>}
      {context.data?.canPost && row.status === "approved" && <Button className="min-h-11" disabled={busy} onClick={() => { if (window.confirm(ar ? "سيُحدّث هذا الإجراء المخزون بشكل ذري. متابعة؟" : "Post stock adjustments atomically? Continue?")) post.mutate({ branchId, countId, idempotencyKey: `count-post:${row.id}` }); }}>{ar ? "ترحيل التسويات" : "Post adjustments"}</Button>}
      {context.data?.canCancel && ["draft", "counting", "submitted", "approved"].includes(row.status) && <Button variant="outline" className="min-h-11" disabled={busy || reason.trim().length < 3} onClick={() => { if (window.confirm(ar ? "إلغاء الجرد؟" : "Cancel this count?")) cancel.mutate({ branchId, countId, reason, idempotencyKey: `count-cancel:${row.id}` }); }}>{ar ? "إلغاء" : "Cancel"}</Button>}
      {context.data?.canReverse && row.status === "posted" && <Button variant="destructive" className="min-h-11" disabled={busy || reason.trim().length < 3} onClick={() => { if (window.confirm(ar ? "إنشاء حركات عكسية؟" : "Create append-only compensating stock movements?")) reverse.mutate({ branchId, countId, reason, idempotencyKey: `count-reverse:${row.id}` }); }}>{ar ? "عكس الجرد" : "Reverse count"}</Button>}</div>}</div>
    <p className="mt-4 text-sm"><Link className="underline" href="/admin/inventory/counts">{ar ? "العودة إلى قائمة الجرد" : "Back to stock counts"}</Link></p>
  </main>;
}
