"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useLocale } from "next-intl";
import { Button } from "@forno/ui/components/button";
import { Card, CardContent, CardHeader, CardTitle } from "@forno/ui/components/card";
import { Input } from "@forno/ui/components/input";
import { Label } from "@forno/ui/components/label";
import { PlusIcon, XIcon } from "lucide-react";
import { toast } from "sonner";
import { useTRPC } from "@/lib/trpc/client";
import { parseDecimalToScaled } from "@/lib/inventory/exact";
import { formatCurrency } from "@/lib/utils";
import { InventoryNav, InventoryPageHeader } from "@/components/inventory/inventory-nav";

type ComponentDraft = { ingredientId: string; locationId: string; unitId: string; quantity: string; modifierOptionId: string };
const emptyComponent = (): ComponentDraft => ({ ingredientId: "", locationId: "", unitId: "", quantity: "", modifierOptionId: "" });

export default function RecipesPage() {
  const trpc = useTRPC(); const client = useQueryClient(); const locale = useLocale(); const ar = locale === "ar";
  const context = useQuery(trpc.inventory.context.queryOptions()); const branchId = context.data?.branch.id ?? 0;
  const refs = useQuery({ ...trpc.inventory.referenceData.queryOptions({ branchId }), enabled: branchId > 0 });
  const ingredients = useQuery({ ...trpc.inventory.ingredients.queryOptions({ branchId }), enabled: branchId > 0 });
  const recipes = useQuery({ ...trpc.inventory.recipes.queryOptions({ branchId }), enabled: branchId > 0 });
  const [menuItemId, setMenuItemId] = useState(""); const [variantId, setVariantId] = useState(""); const [yieldLoss, setYieldLoss] = useState("0"); const [components, setComponents] = useState<ComponentDraft[]>([emptyComponent()]);
  const [orderIdLookup, setOrderIdLookup] = useState("");
  const orderCost = useQuery({ ...trpc.inventory.orderCost.queryOptions({ branchId, orderId: Number(orderIdLookup) || 1 }), enabled: branchId > 0 && Number(orderIdLookup) > 0 });
  const selectedItem = recipes.data?.find((row) => row.id === Number(menuItemId));
  const refresh = () => client.invalidateQueries({ queryKey: trpc.inventory.recipes.queryOptions({ branchId }).queryKey });
  const create = useMutation(trpc.inventory.createRecipe.mutationOptions({ onSuccess: async () => { toast.success(ar ? "تم حفظ نسخة مسودة" : "Draft recipe version saved"); await refresh(); }, onError: (error) => toast.error(error.message) }));
  const activate = useMutation(trpc.inventory.activateRecipe.mutationOptions({ onSuccess: async () => { toast.success(ar ? "تم اعتماد وتفعيل الوصفة" : "Recipe approved and activated"); await refresh(); }, onError: (error) => toast.error(error.message) }));
  const modifierOptions = useMemo(() => refs.data?.modifiers.flatMap((group) => group.options.map((option) => ({ ...option, group: ar ? group.name_ar : group.name_en }))) ?? [], [refs.data, ar]);
  const updateComponent = (index: number, patch: Partial<ComponentDraft>) => setComponents((rows) => rows.map((row, rowIndex) => rowIndex === index ? { ...row, ...patch } : row));
  const submit = () => {
    try {
      create.mutate({ branchId, menuItemId: Number(menuItemId), variantId: variantId ? Number(variantId) : null, yieldLossBps: Number(yieldLoss), components: components.map((row) => ({ ingredientId: Number(row.ingredientId), locationId: Number(row.locationId), unitId: Number(row.unitId), quantityScaled: row.quantity.startsWith("-") ? -parseDecimalToScaled(row.quantity.slice(1)) : parseDecimalToScaled(row.quantity), modifierOptionId: row.modifierOptionId ? Number(row.modifierOptionId) : null })) });
    } catch (error) { toast.error(error instanceof Error ? error.message : "Invalid component quantity"); }
  };
  return <div><InventoryNav /><InventoryPageHeader titleEn="Recipe builder and theoretical cost" titleAr="بناء الوصفات والتكلفة النظرية" descriptionEn="Versioned recipes resolve variants and modifier deltas into immutable order consumption and COGS snapshots." descriptionAr="وصفات بإصدارات تربط الأحجام والإضافات بلقطات استهلاك وتكلفة تاريخية ثابتة." />
    <div className="grid gap-4 xl:grid-cols-[1fr_420px]">
      <Card><CardHeader><CardTitle>{ar ? "تغطية المنيو والإصدارات" : "Menu coverage and version history"}</CardTitle></CardHeader><CardContent className="space-y-3">{recipes.data?.map((item) => <div key={item.id} className="rounded-lg border p-3"><div className="flex flex-wrap items-center justify-between gap-2"><strong>{ar ? item.name_ar : item.name_en}</strong><span className="text-xs text-muted-foreground">{item.code}</span></div><div className="mt-2 grid gap-2 sm:grid-cols-2">{item.availability.map((availability) => <div key={`${availability.menuItemId}:${availability.variantId}`} className="rounded bg-muted p-2 text-sm"><div className="flex justify-between"><span>{availability.variantId ? item.variants.find((variant) => variant.id === availability.variantId)?.code : (ar ? "أساسي" : "Base")}</span><strong className={availability.status === "out_of_stock" || availability.status === "recipe_missing" ? "text-destructive" : availability.status === "low_stock" ? "text-amber-700" : "text-emerald-700"}>{availability.status.replaceAll("_", " ")}</strong></div><div className="mt-1 flex justify-between text-muted-foreground"><span>{ar ? "أقصى إنتاج" : "Max producible"}: {availability.maxProducible}</span>{availability.theoreticalCost != null && <span>{formatCurrency(availability.theoreticalCost, locale)}</span>}</div></div>)}</div>
          <div className="mt-2 space-y-1">{item.recipeVersions.map((version) => <div key={version.id} className="flex min-h-10 items-center justify-between border-t text-sm"><span>v{version.version} · {version.variant_id ? item.variants.find((variant) => variant.id === version.variant_id)?.code : "base"} · {version.components.length} {ar ? "مكونات" : "components"}{version.theoreticalBaseCost != null && <> · {formatCurrency(version.theoreticalBaseCost, locale)} + {version.modifierIncrementalCosts.length} {ar ? "تأثيرات إضافات" : "modifier effects"}</>}</span><span className="flex items-center gap-2"><strong>{version.status}</strong>{version.status === "draft" && context.data?.canManageRecipes && <Button size="sm" onClick={() => activate.mutate({ branchId, recipeVersionId: version.id, reason: "Recipe reviewed and approved" })}>{ar ? "اعتماد وتفعيل" : "Approve & activate"}</Button>}</span></div>)}</div></div>)}</CardContent></Card>
      {context.data?.canManageRecipes && <Card><CardHeader><CardTitle>{ar ? "نسخة وصفة جديدة" : "New recipe version"}</CardTitle></CardHeader><CardContent className="space-y-3">
        <Field label={ar ? "عنصر المنيو" : "Menu item"}><select className="min-h-11 w-full rounded-md border bg-background px-3" value={menuItemId} onChange={(e) => { setMenuItemId(e.target.value); setVariantId(""); }}><option value="">—</option>{recipes.data?.map((item) => <option value={item.id} key={item.id}>{ar ? item.name_ar : item.name_en}</option>)}</select></Field>
        <Field label={ar ? "الحجم/النوع" : "Variant / base"}><select className="min-h-11 w-full rounded-md border bg-background px-3" value={variantId} onChange={(e) => setVariantId(e.target.value)}><option value="">{ar ? "وصفة أساسية" : "Base recipe"}</option>{selectedItem?.variants.map((variant) => <option key={variant.id} value={variant.id}>{ar ? variant.name_ar : variant.name_en}</option>)}</select></Field>
        <Field label={ar ? "فاقد التحضير (نقطة أساس)" : "Yield loss (basis points)"}><Input type="number" min={0} max={9999} value={yieldLoss} onChange={(e) => setYieldLoss(e.target.value)} /></Field>
        <div className="space-y-3">{components.map((row, index) => { const ingredient = ingredients.data?.find((entry) => entry.id === Number(row.ingredientId)); return <div className="rounded-lg border p-3" key={index}><div className="mb-2 flex justify-between"><strong>{ar ? `مكون ${index + 1}` : `Component ${index + 1}`}</strong>{components.length > 1 && <Button variant="ghost" size="icon" aria-label="Remove component" onClick={() => setComponents((values) => values.filter((_, rowIndex) => rowIndex !== index))}><XIcon className="h-4 w-4" /></Button>}</div>
          <select aria-label="Ingredient" className="mb-2 min-h-11 w-full rounded-md border bg-background px-3" value={row.ingredientId} onChange={(e) => { const selected = ingredients.data?.find((entry) => entry.id === Number(e.target.value)); const unit = refs.data?.units.find((entry) => entry.dimension === selected?.dimension && ["G", "ML", "PC"].includes(entry.code)); updateComponent(index, { ingredientId: e.target.value, locationId: String(selected?.default_location_id ?? ""), unitId: String(unit?.id ?? "") }); }}><option value="">{ar ? "اختر المكون" : "Select ingredient"}</option>{ingredients.data?.map((entry) => <option value={entry.id} key={entry.id}>{ar ? entry.name_ar : entry.name_en}</option>)}</select>
          <div className="grid grid-cols-2 gap-2"><Input aria-label="Quantity" inputMode="decimal" placeholder={ar ? "الكمية" : "Quantity"} value={row.quantity} onChange={(e) => updateComponent(index, { quantity: e.target.value })} /><select aria-label="Unit" className="min-h-11 rounded-md border bg-background px-3" value={row.unitId} onChange={(e) => updateComponent(index, { unitId: e.target.value })}>{refs.data?.units.filter((unit) => unit.dimension === ingredient?.dimension).map((unit) => <option value={unit.id} key={unit.id}>{unit.code}</option>)}</select></div>
          <select aria-label="Modifier effect" className="mt-2 min-h-11 w-full rounded-md border bg-background px-3" value={row.modifierOptionId} onChange={(e) => updateComponent(index, { modifierOptionId: e.target.value })}><option value="">{ar ? "مكون أساسي" : "Base component"}</option>{modifierOptions.map((option) => <option key={option.id} value={option.id}>{option.group}: {ar ? option.name_ar : option.name_en}</option>)}</select>
        </div>; })}</div>
        <Button variant="outline" className="min-h-11 w-full" onClick={() => setComponents((rows) => [...rows, emptyComponent()])}><PlusIcon className="me-2 h-4 w-4" />{ar ? "إضافة مكون" : "Add component"}</Button><Button className="min-h-11 w-full" disabled={!menuItemId || components.some((row) => !row.ingredientId || !row.locationId || !row.unitId || !row.quantity)} onClick={submit}>{ar ? "حفظ نسخة مسودة" : "Save draft version"}</Button>
      </CardContent></Card>}
    </div>
    <Card className="mt-4"><CardHeader><CardTitle>{ar ? "لقطة تكلفة طلب تاريخية" : "Immutable historical order COGS"}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input inputMode="numeric" value={orderIdLookup} onChange={(event) => setOrderIdLookup(event.target.value)} placeholder={ar ? "رقم الطلب" : "Order ID"} /><Button variant="outline" onClick={() => orderCost.refetch()} disabled={!orderIdLookup}>{ar ? "عرض" : "View snapshot"}</Button></div>{orderCost.data && <div className="grid gap-2 sm:grid-cols-3"><div className="rounded bg-muted p-3"><small>{ar ? "صافي البيع" : "Net sale"}</small><strong className="block">{formatCurrency(orderCost.data.netSale, locale)}</strong></div><div className="rounded bg-muted p-3"><small>{ar ? "التكلفة النظرية الثابتة" : "Immutable COGS"}</small><strong className="block">{orderCost.data.totalCogs == null ? "—" : formatCurrency(orderCost.data.totalCogs, locale)}</strong></div><div className="rounded bg-muted p-3"><small>{ar ? "الهامش النظري" : "Theoretical gross margin"}</small><strong className="block">{orderCost.data.theoreticalGrossMargin == null ? "—" : formatCurrency(orderCost.data.theoreticalGrossMargin, locale)}</strong></div>{orderCost.data.items.map((item) => <div key={item.id} className="rounded border p-3 text-sm"><strong>{ar ? item.name_ar : item.name_en}</strong><span className="block text-muted-foreground">v{item.recipeVersion ?? "—"} · {item.cogs == null ? "—" : formatCurrency(item.cogs, locale)}</span></div>)}</div>}</CardContent></Card>
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1"><Label>{label}</Label>{children}</div>; }
