import { bigint, boolean, check, index, integer, pgTable, serial, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { InventoryDimension, RecipeStatus, PurchaseOrderStatus, PurchaseOrderReceivingStatus, PurchaseReceiptStatus, SupplierReturnStatus, SupplierReturnReason, StockTransferStatus, StockCountStatus, StockMovementType } from "./constants";
import { branches, suppliers, menuItems, menuItemVariants, modifierOptions } from "./restaurant";
import { orders, orderItems } from "./orders";
import { user } from "../auth-schema";

export const inventoryLocations = pgTable(
  "inventory_locations",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    code: varchar("code", { length: 32 }).notNull(),
    name_en: varchar("name_en", { length: 100 }).notNull(),
    name_ar: varchar("name_ar", { length: 100 }).notNull(),
    is_active: boolean("is_active").default(true).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [uniqueIndex("inventory_locations_branch_code_uidx").on(table.branch_id, table.code), index("inventory_locations_branch_idx").on(table.branch_id)],
);

export const ingredientCategories = pgTable(
  "ingredient_categories",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    code: varchar("code", { length: 32 }).notNull(),
    name_en: varchar("name_en", { length: 100 }).notNull(),
    name_ar: varchar("name_ar", { length: 100 }).notNull(),
    is_active: boolean("is_active").default(true).notNull(),
  },
  (table) => [uniqueIndex("ingredient_categories_branch_code_uidx").on(table.branch_id, table.code)],
);

export const unitsOfMeasure = pgTable(
  "units_of_measure",
  {
    id: serial("id").primaryKey(),
    code: varchar("code", { length: 20 }).notNull(),
    name_en: varchar("name_en", { length: 60 }).notNull(),
    name_ar: varchar("name_ar", { length: 60 }).notNull(),
    dimension: varchar("dimension", { length: 12 }).$type<InventoryDimension>().notNull(),
    base_numerator: bigint("base_numerator", { mode: "number" }).notNull(),
    base_denominator: bigint("base_denominator", { mode: "number" }).notNull(),
  },
  (table) => [
    uniqueIndex("units_of_measure_code_uidx").on(table.code),
    check("units_of_measure_dimension_check", sql`${table.dimension} in ('mass', 'volume', 'count')`),
    check("units_of_measure_factor_check", sql`${table.base_numerator} > 0 and ${table.base_denominator} > 0`),
  ],
);

export const ingredients = pgTable(
  "ingredients",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    category_id: integer("category_id").notNull().references(() => ingredientCategories.id, { onDelete: "restrict" }),
    sku: varchar("sku", { length: 40 }).notNull(),
    name_en: varchar("name_en", { length: 120 }).notNull(),
    name_ar: varchar("name_ar", { length: 120 }).notNull(),
    base_unit_id: integer("base_unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    dimension: varchar("dimension", { length: 12 }).$type<InventoryDimension>().notNull(),
    default_location_id: integer("default_location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    is_active: boolean("is_active").default(true).notNull(),
    is_tracked: boolean("is_tracked").default(true).notNull(),
    reorder_level: bigint("reorder_level", { mode: "number" }).default(0).notNull(),
    low_stock_threshold: bigint("low_stock_threshold", { mode: "number" }).default(0).notNull(),
    par_level: bigint("par_level", { mode: "number" }),
    allow_negative: boolean("allow_negative").default(false).notNull(),
    average_unit_cost_micros: bigint("average_unit_cost_micros", { mode: "number" }).default(0).notNull(),
    created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    updated_by: text("updated_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("ingredients_branch_sku_uidx").on(table.branch_id, table.sku),
    index("ingredients_branch_category_idx").on(table.branch_id, table.category_id),
    check("ingredients_dimension_check", sql`${table.dimension} in ('mass', 'volume', 'count')`),
    check("ingredients_thresholds_check", sql`${table.reorder_level} >= 0 and ${table.low_stock_threshold} >= 0 and (${table.par_level} is null or ${table.par_level} >= 0)`),
    check("ingredients_average_cost_check", sql`${table.average_unit_cost_micros} >= 0`),
  ],
);

export const ingredientPackageConversions = pgTable(
  "ingredient_package_conversions",
  {
    id: serial("id").primaryKey(),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    code: varchar("code", { length: 24 }).notNull(),
    name_en: varchar("name_en", { length: 60 }).notNull(),
    name_ar: varchar("name_ar", { length: 60 }).notNull(),
    base_numerator: bigint("base_numerator", { mode: "number" }).notNull(),
    base_denominator: bigint("base_denominator", { mode: "number" }).notNull(),
    is_active: boolean("is_active").default(true).notNull(),
  },
  (table) => [
    uniqueIndex("ingredient_packages_ingredient_code_uidx").on(table.ingredient_id, table.code),
    check("ingredient_packages_factor_check", sql`${table.base_numerator} > 0 and ${table.base_denominator} > 0`),
  ],
);

export const purchaseOrders = pgTable(
  "purchase_orders",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    supplier_id: integer("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }),
    supplier_code_snapshot: varchar("supplier_code_snapshot", { length: 40 }).notNull(),
    supplier_name_en_snapshot: varchar("supplier_name_en_snapshot", { length: 160 }).notNull(),
    supplier_name_ar_snapshot: varchar("supplier_name_ar_snapshot", { length: 160 }).notNull(),
    po_number: varchar("po_number", { length: 48 }).notNull(),
      status: varchar("status", { length: 20 }).$type<PurchaseOrderStatus>().default("draft").notNull(),
      receiving_status: varchar("receiving_status", { length: 24 }).$type<PurchaseOrderReceivingStatus>().default("not_received").notNull(),
    order_date: timestamp("order_date").defaultNow().notNull(),
    expected_date: timestamp("expected_date"),
    currency: varchar("currency", { length: 3 }).default("EGP").notNull(),
    subtotal_amount: integer("subtotal_amount").default(0).notNull(),
    total_amount: integer("total_amount").default(0).notNull(),
    notes: text("notes"),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    submitted_by: text("submitted_by").references(() => user.id, { onDelete: "restrict" }),
    approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
    cancelled_by: text("cancelled_by").references(() => user.id, { onDelete: "restrict" }),
    cancellation_reason: text("cancellation_reason"),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_orders_branch_number_uidx").on(table.branch_id, table.po_number),
    uniqueIndex("purchase_orders_idempotency_uidx").on(table.idempotency_key),
    index("purchase_orders_branch_status_created_idx").on(table.branch_id, table.status, table.created_at),
      check("purchase_orders_status_check", sql`${table.status} in ('draft', 'submitted', 'approved', 'cancelled')`),
      check("purchase_orders_receiving_status_check", sql`${table.receiving_status} in ('not_received', 'partially_received', 'fully_received')`),
    check("purchase_orders_amounts_check", sql`${table.subtotal_amount} >= 0 and ${table.total_amount} = ${table.subtotal_amount} and ${table.subtotal_amount} <= 2147483647`),
  ],
);

export const purchaseOrderLines = pgTable(
  "purchase_order_lines",
  {
    id: serial("id").primaryKey(),
    purchase_order_id: integer("purchase_order_id").notNull().references(() => purchaseOrders.id, { onDelete: "cascade" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    ingredient_sku: varchar("ingredient_sku", { length: 40 }).notNull(),
    ingredient_name_en: varchar("ingredient_name_en", { length: 160 }).notNull(),
    ingredient_name_ar: varchar("ingredient_name_ar", { length: 160 }).notNull(),
    unit_code: varchar("unit_code", { length: 24 }).notNull(),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
      quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
      conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }),
      conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }),
    unit_price_minor: integer("unit_price_minor").notNull(),
    line_total_amount: integer("line_total_amount").notNull(),
    notes: text("notes"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("purchase_order_lines_order_idx").on(table.purchase_order_id),
    index("purchase_order_lines_ingredient_idx").on(table.ingredient_id),
      check("purchase_order_lines_values_check", sql`${table.quantity_input_scaled} > 0 and ${table.quantity_base} > 0 and ${table.unit_price_minor} >= 0 and ${table.line_total_amount} >= 0 and ${table.line_total_amount} <= 2147483647`),
      check("purchase_order_lines_conversion_snapshot_check", sql`(${table.conversion_numerator_snapshot} is null and ${table.conversion_denominator_snapshot} is null) or (${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0)`),
    ],
  );

export const purchaseReceipts = pgTable(
  "purchase_receipts",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    purchase_order_id: integer("purchase_order_id").notNull().references(() => purchaseOrders.id, { onDelete: "restrict" }),
    supplier_id: integer("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }),
    supplier_code_snapshot: varchar("supplier_code_snapshot", { length: 40 }).notNull(),
    supplier_name_en_snapshot: varchar("supplier_name_en_snapshot", { length: 160 }).notNull(),
    supplier_name_ar_snapshot: varchar("supplier_name_ar_snapshot", { length: 160 }).notNull(),
    po_number_snapshot: varchar("po_number_snapshot", { length: 48 }).notNull(),
    receipt_number: varchar("receipt_number", { length: 48 }).notNull(),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    supplier_delivery_note: varchar("supplier_delivery_note", { length: 120 }),
    supplier_invoice_reference: varchar("supplier_invoice_reference", { length: 120 }),
    received_at: timestamp("received_at").defaultNow().notNull(),
    received_by: text("received_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    notes: text("notes"),
    status: varchar("status", { length: 20 }).$type<PurchaseReceiptStatus>().default("draft").notNull(),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    posted_at: timestamp("posted_at"),
    posted_by: text("posted_by").references(() => user.id, { onDelete: "restrict" }),
    variance_approved_by: text("variance_approved_by").references(() => user.id, { onDelete: "restrict" }),
    variance_reason: text("variance_reason"),
    overreceive_approved_by: text("overreceive_approved_by").references(() => user.id, { onDelete: "restrict" }),
    overreceive_reason: text("overreceive_reason"),
    reversal_reason: text("reversal_reason"),
    needs_review_reason: text("needs_review_reason"),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_receipts_branch_number_uidx").on(table.branch_id, table.receipt_number),
    uniqueIndex("purchase_receipts_idempotency_uidx").on(table.idempotency_key),
    index("purchase_receipts_branch_status_created_idx").on(table.branch_id, table.status, table.created_at),
    index("purchase_receipts_po_idx").on(table.purchase_order_id, table.created_at),
    check("purchase_receipts_status_check", sql`${table.status} in ('draft', 'posted', 'reversed', 'needs_review')`),
    check("purchase_receipts_reversal_reason_check", sql`${table.status} not in ('reversed', 'needs_review') or length(trim(coalesce(${table.reversal_reason}, ${table.needs_review_reason}, ''))) > 0`),
  ],
);

export const purchaseReceiptLines = pgTable(
  "purchase_receipt_lines",
  {
    id: serial("id").primaryKey(),
    receipt_id: integer("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    purchase_order_line_id: integer("purchase_order_line_id").notNull().references(() => purchaseOrderLines.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    ingredient_sku_snapshot: varchar("ingredient_sku_snapshot", { length: 40 }).notNull(),
    ingredient_name_en_snapshot: varchar("ingredient_name_en_snapshot", { length: 160 }).notNull(),
    ingredient_name_ar_snapshot: varchar("ingredient_name_ar_snapshot", { length: 160 }).notNull(),
    package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    unit_code_snapshot: varchar("unit_code_snapshot", { length: 24 }).notNull(),
    conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
    conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
    ordered_quantity_base_snapshot: bigint("ordered_quantity_base_snapshot", { mode: "number" }).notNull(),
    po_unit_price_minor_snapshot: integer("po_unit_price_minor_snapshot").notNull(),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
    accepted_quantity_base: bigint("accepted_quantity_base", { mode: "number" }).notNull(),
    rejected_quantity_base: bigint("rejected_quantity_base", { mode: "number" }).notNull(),
    damaged_quantity_base: bigint("damaged_quantity_base", { mode: "number" }).notNull(),
    actual_unit_price_minor: integer("actual_unit_price_minor").notNull(),
    accepted_unit_cost_micros_snapshot: bigint("accepted_unit_cost_micros_snapshot", { mode: "number" }).notNull(),
    balance_quantity_before: bigint("balance_quantity_before", { mode: "number" }),
    balance_unit_cost_before: bigint("balance_unit_cost_before", { mode: "number" }),
    ingredient_average_unit_cost_before: bigint("ingredient_average_unit_cost_before", { mode: "number" }),
    line_total_amount: integer("line_total_amount").notNull(),
    notes: text("notes"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_receipt_lines_receipt_po_line_uidx").on(table.receipt_id, table.purchase_order_line_id),
    index("purchase_receipt_lines_po_line_idx").on(table.purchase_order_line_id),
    check("purchase_receipt_lines_conversion_check", sql`${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`),
    check("purchase_receipt_lines_values_check", sql`${table.quantity_input_scaled} > 0 and ${table.accepted_quantity_base} >= 0 and ${table.rejected_quantity_base} >= 0 and ${table.damaged_quantity_base} >= 0 and ${table.actual_unit_price_minor} >= 0 and ${table.po_unit_price_minor_snapshot} >= 0 and ${table.accepted_unit_cost_micros_snapshot} >= 0 and ${table.line_total_amount} >= 0 and ${table.line_total_amount} <= 2147483647`),
  ],
);

export const purchaseReceiptReversals = pgTable(
  "purchase_receipt_reversals",
  {
    id: serial("id").primaryKey(),
    receipt_id: integer("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    reason: text("reason").notNull(),
    status: varchar("status", { length: 16 }).notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_receipt_reversals_receipt_uidx").on(table.receipt_id),
    uniqueIndex("purchase_receipt_reversals_idempotency_uidx").on(table.idempotency_key),
    check("purchase_receipt_reversals_reason_check", sql`length(trim(${table.reason})) >= 3`),
    check("purchase_receipt_reversals_status_check", sql`${table.status} in ('reversed', 'needs_review')`),
  ],
);

export const supplierReturns = pgTable(
  "supplier_returns",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    supplier_id: integer("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }),
    purchase_order_id: integer("purchase_order_id").notNull().references(() => purchaseOrders.id, { onDelete: "restrict" }),
    receipt_id: integer("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    return_number: varchar("return_number", { length: 48 }).notNull(),
    supplier_code_snapshot: varchar("supplier_code_snapshot", { length: 40 }).notNull(),
    supplier_name_en_snapshot: varchar("supplier_name_en_snapshot", { length: 160 }).notNull(),
    supplier_name_ar_snapshot: varchar("supplier_name_ar_snapshot", { length: 160 }).notNull(),
    po_number_snapshot: varchar("po_number_snapshot", { length: 48 }).notNull(),
    receipt_number_snapshot: varchar("receipt_number_snapshot", { length: 48 }).notNull(),
    reason_code: varchar("reason_code", { length: 24 }).$type<SupplierReturnReason>().notNull(),
    reason: text("reason"),
    notes: text("notes"),
    evidence_metadata: text("evidence_metadata"),
    status: varchar("status", { length: 20 }).$type<SupplierReturnStatus>().default("draft").notNull(),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    expected_credit_amount: integer("expected_credit_amount").default(0).notNull(),
    valuation_amount: integer("valuation_amount"),
    cost_variance_amount: integer("cost_variance_amount"),
    created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    submitted_by: text("submitted_by").references(() => user.id, { onDelete: "restrict" }),
    approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
    dispatched_by: text("dispatched_by").references(() => user.id, { onDelete: "restrict" }),
    cancelled_by: text("cancelled_by").references(() => user.id, { onDelete: "restrict" }),
    reversed_by: text("reversed_by").references(() => user.id, { onDelete: "restrict" }),
    submitted_at: timestamp("submitted_at"),
    approved_at: timestamp("approved_at"),
    dispatched_at: timestamp("dispatched_at"),
    cancelled_at: timestamp("cancelled_at"),
    reversed_at: timestamp("reversed_at"),
    cancellation_reason: text("cancellation_reason"),
    needs_review_reason: text("needs_review_reason"),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_returns_branch_number_uidx").on(table.branch_id, table.return_number),
    uniqueIndex("supplier_returns_idempotency_uidx").on(table.idempotency_key),
    index("supplier_returns_branch_status_created_idx").on(table.branch_id, table.status, table.created_at),
    index("supplier_returns_receipt_idx").on(table.receipt_id, table.created_at),
    check("supplier_returns_status_check", sql`${table.status} in ('draft', 'submitted', 'approved', 'dispatched', 'cancelled', 'needs_review', 'reversed')`),
    check("supplier_returns_reason_check", sql`${table.reason_code} in ('damaged', 'expired', 'wrong_item', 'quality_issue', 'over_delivery', 'other')`),
    check("supplier_returns_money_check", sql`${table.expected_credit_amount} >= 0 and (${table.valuation_amount} is null or ${table.valuation_amount} >= 0) and (${table.cost_variance_amount} is null or ${table.cost_variance_amount} between -2147483647 and 2147483647)`),
    check("supplier_returns_review_reason_check", sql`${table.status} <> 'needs_review' or length(trim(coalesce(${table.needs_review_reason}, ''))) > 0`),
  ],
);

export const supplierReturnLines = pgTable(
  "supplier_return_lines",
  {
    id: serial("id").primaryKey(),
    supplier_return_id: integer("supplier_return_id").notNull().references(() => supplierReturns.id, { onDelete: "restrict" }),
    receipt_line_id: integer("receipt_line_id").notNull().references(() => purchaseReceiptLines.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    ingredient_sku_snapshot: varchar("ingredient_sku_snapshot", { length: 40 }).notNull(),
    ingredient_name_en_snapshot: varchar("ingredient_name_en_snapshot", { length: 160 }).notNull(),
    ingredient_name_ar_snapshot: varchar("ingredient_name_ar_snapshot", { length: 160 }).notNull(),
    dimension_snapshot: varchar("dimension_snapshot", { length: 16 }).notNull(),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    unit_code_snapshot: varchar("unit_code_snapshot", { length: 24 }).notNull(),
    package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
    conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
    conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
    quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
    accepted_quantity_base_snapshot: bigint("accepted_quantity_base_snapshot", { mode: "number" }).notNull(),
    original_unit_cost_micros_snapshot: bigint("original_unit_cost_micros_snapshot", { mode: "number" }).notNull(),
    expected_credit_amount: integer("expected_credit_amount").notNull(),
    dispatch_unit_cost_micros_snapshot: bigint("dispatch_unit_cost_micros_snapshot", { mode: "number" }),
    dispatch_valuation_amount: integer("dispatch_valuation_amount"),
    notes: text("notes"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_return_lines_return_receipt_line_uidx").on(table.supplier_return_id, table.receipt_line_id),
    index("supplier_return_lines_receipt_line_idx").on(table.receipt_line_id),
    check("supplier_return_lines_conversion_check", sql`${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`),
    check("supplier_return_lines_dimension_check", sql`${table.dimension_snapshot} in ('mass', 'volume', 'count')`),
    check("supplier_return_lines_quantities_check", sql`${table.quantity_input_scaled} > 0 and ${table.quantity_base} > 0 and ${table.accepted_quantity_base_snapshot} >= ${table.quantity_base}`),
    check("supplier_return_lines_cost_check", sql`${table.original_unit_cost_micros_snapshot} >= 0 and ${table.expected_credit_amount} >= 0 and (${table.dispatch_unit_cost_micros_snapshot} is null or ${table.dispatch_unit_cost_micros_snapshot} >= 0) and (${table.dispatch_valuation_amount} is null or ${table.dispatch_valuation_amount} >= 0)`),
  ],
);

export const supplierReturnStatusHistory = pgTable(
  "supplier_return_status_history",
  {
    id: serial("id").primaryKey(),
    supplier_return_id: integer("supplier_return_id").notNull().references(() => supplierReturns.id, { onDelete: "restrict" }),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    from_status: varchar("from_status", { length: 20 }),
    to_status: varchar("to_status", { length: 20 }).$type<SupplierReturnStatus>().notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    reason: text("reason"),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_return_status_history_idempotency_uidx").on(table.idempotency_key),
    index("supplier_return_status_history_return_idx").on(table.supplier_return_id, table.created_at),
  ],
);

export const supplierReturnReversals = pgTable(
  "supplier_return_reversals",
  {
    id: serial("id").primaryKey(),
    supplier_return_id: integer("supplier_return_id").notNull().references(() => supplierReturns.id, { onDelete: "restrict" }),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    reason: text("reason").notNull(),
    status: varchar("status", { length: 16 }).notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_return_reversals_return_uidx").on(table.supplier_return_id),
    uniqueIndex("supplier_return_reversals_idempotency_uidx").on(table.idempotency_key),
    check("supplier_return_reversals_reason_check", sql`length(trim(${table.reason})) >= 3`),
    check("supplier_return_reversals_status_check", sql`${table.status} in ('reversed', 'needs_review')`),
  ],
);

export const stockTransfers = pgTable("stock_transfers", {
  id: serial("id").primaryKey(),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  transfer_number: varchar("transfer_number", { length: 48 }).notNull(),
  source_location_id: integer("source_location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
  destination_location_id: integer("destination_location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
  source_code_snapshot: varchar("source_code_snapshot", { length: 32 }).notNull(),
  source_name_en_snapshot: varchar("source_name_en_snapshot", { length: 100 }).notNull(),
  source_name_ar_snapshot: varchar("source_name_ar_snapshot", { length: 100 }).notNull(),
  destination_code_snapshot: varchar("destination_code_snapshot", { length: 32 }).notNull(),
  destination_name_en_snapshot: varchar("destination_name_en_snapshot", { length: 100 }).notNull(),
  destination_name_ar_snapshot: varchar("destination_name_ar_snapshot", { length: 100 }).notNull(),
  status: varchar("status", { length: 24 }).$type<StockTransferStatus>().default("draft").notNull(),
  notes: text("notes"),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
  submitted_by: text("submitted_by").references(() => user.id, { onDelete: "restrict" }),
  approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
  cancelled_by: text("cancelled_by").references(() => user.id, { onDelete: "restrict" }),
  dispatched_by: text("dispatched_by").references(() => user.id, { onDelete: "restrict" }),
  dispatched_at: timestamp("dispatched_at"),
  received_at: timestamp("received_at"),
  cancellation_reason: text("cancellation_reason"),
  needs_review_reason: text("needs_review_reason"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
}, (table) => [
  uniqueIndex("stock_transfers_branch_number_uidx").on(table.branch_id, table.transfer_number),
  uniqueIndex("stock_transfers_idempotency_uidx").on(table.idempotency_key),
  index("stock_transfers_branch_status_idx").on(table.branch_id, table.status),
  check("stock_transfers_locations_check", sql`${table.source_location_id} <> ${table.destination_location_id}`),
  check("stock_transfers_status_check", sql`${table.status} in ('draft', 'submitted', 'approved', 'dispatched', 'partially_received', 'received', 'cancelled', 'needs_review', 'reversed')`),
]);

export const stockTransferLines = pgTable("stock_transfer_lines", {
  id: serial("id").primaryKey(),
  transfer_id: integer("transfer_id").notNull().references(() => stockTransfers.id, { onDelete: "restrict" }),
  ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
  ingredient_sku_snapshot: varchar("ingredient_sku_snapshot", { length: 40 }).notNull(),
  ingredient_name_en_snapshot: varchar("ingredient_name_en_snapshot", { length: 160 }).notNull(),
  ingredient_name_ar_snapshot: varchar("ingredient_name_ar_snapshot", { length: 160 }).notNull(),
  dimension_snapshot: varchar("dimension_snapshot", { length: 16 }).notNull(),
  unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
  unit_code_snapshot: varchar("unit_code_snapshot", { length: 24 }).notNull(),
  package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
  package_code_snapshot: varchar("package_code_snapshot", { length: 24 }),
  package_name_en_snapshot: varchar("package_name_en_snapshot", { length: 60 }),
  package_name_ar_snapshot: varchar("package_name_ar_snapshot", { length: 60 }),
  conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
  conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
  quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
  quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
  notes: text("notes"),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  uniqueIndex("stock_transfer_lines_transfer_ingredient_uidx").on(table.transfer_id, table.ingredient_id),
  check("stock_transfer_lines_conversion_check", sql`${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`),
  check("stock_transfer_lines_quantity_check", sql`${table.quantity_input_scaled} > 0 and ${table.quantity_base} > 0`),
  check("stock_transfer_lines_dimension_check", sql`${table.dimension_snapshot} in ('mass', 'volume', 'count')`),
]);

export const stockTransferDispatches = pgTable("stock_transfer_dispatches", {
  id: serial("id").primaryKey(),
  transfer_id: integer("transfer_id").notNull().references(() => stockTransfers.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  reason: text("reason"),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_transfer_dispatches_transfer_uidx").on(table.transfer_id), uniqueIndex("stock_transfer_dispatches_idempotency_uidx").on(table.idempotency_key)]);

export const stockTransferDispatchLines = pgTable("stock_transfer_dispatch_lines", {
  id: serial("id").primaryKey(),
  dispatch_id: integer("dispatch_id").notNull().references(() => stockTransferDispatches.id, { onDelete: "restrict" }),
  transfer_line_id: integer("transfer_line_id").notNull().references(() => stockTransferLines.id, { onDelete: "restrict" }),
  quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
  unit_cost_micros_snapshot: bigint("unit_cost_micros_snapshot", { mode: "number" }).notNull(),
  total_cost_amount: integer("total_cost_amount").notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_transfer_dispatch_lines_transfer_line_uidx").on(table.transfer_line_id), check("stock_transfer_dispatch_lines_values_check", sql`${table.quantity_base} > 0 and ${table.unit_cost_micros_snapshot} >= 0 and ${table.total_cost_amount} >= 0`)]);

export const stockTransferReceipts = pgTable("stock_transfer_receipts", {
  id: serial("id").primaryKey(),
  transfer_id: integer("transfer_id").notNull().references(() => stockTransfers.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  reason: text("reason"),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_transfer_receipts_idempotency_uidx").on(table.idempotency_key), index("stock_transfer_receipts_transfer_idx").on(table.transfer_id, table.created_at)]);

export const stockTransferReceiptLines = pgTable("stock_transfer_receipt_lines", {
  id: serial("id").primaryKey(),
  receipt_id: integer("receipt_id").notNull().references(() => stockTransferReceipts.id, { onDelete: "restrict" }),
  transfer_line_id: integer("transfer_line_id").notNull().references(() => stockTransferLines.id, { onDelete: "restrict" }),
  quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
  unit_cost_micros_snapshot: bigint("unit_cost_micros_snapshot", { mode: "number" }).notNull(),
  total_cost_amount: integer("total_cost_amount").notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [check("stock_transfer_receipt_lines_values_check", sql`${table.quantity_base} > 0 and ${table.unit_cost_micros_snapshot} >= 0 and ${table.total_cost_amount} >= 0`)]);

export const stockTransferReversals = pgTable("stock_transfer_reversals", {
  id: serial("id").primaryKey(),
  transfer_id: integer("transfer_id").notNull().references(() => stockTransfers.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  status: varchar("status", { length: 16 }).notNull(),
  reason: text("reason").notNull(),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_transfer_reversals_transfer_uidx").on(table.transfer_id), uniqueIndex("stock_transfer_reversals_idempotency_uidx").on(table.idempotency_key), check("stock_transfer_reversals_status_check", sql`${table.status} in ('reversed', 'needs_review')`)]);

export const stockTransferStatusHistory = pgTable("stock_transfer_status_history", {
  id: serial("id").primaryKey(),
  transfer_id: integer("transfer_id").notNull().references(() => stockTransfers.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  from_status: varchar("from_status", { length: 24 }),
  to_status: varchar("to_status", { length: 24 }).$type<StockTransferStatus>().notNull(),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  reason: text("reason"),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_transfer_status_history_idempotency_uidx").on(table.idempotency_key), index("stock_transfer_status_history_transfer_idx").on(table.transfer_id, table.created_at)]);

export const stockCounts = pgTable("stock_counts", {
  id: serial("id").primaryKey(),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
  count_number: varchar("count_number", { length: 48 }).notNull(),
  status: varchar("status", { length: 20 }).$type<StockCountStatus>().default("draft").notNull(),
  notes: text("notes"),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
  started_by: text("started_by").references(() => user.id, { onDelete: "restrict" }),
  started_at: timestamp("started_at"),
  submitted_by: text("submitted_by").references(() => user.id, { onDelete: "restrict" }),
  submitted_at: timestamp("submitted_at"),
  approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
  approved_at: timestamp("approved_at"),
  posted_by: text("posted_by").references(() => user.id, { onDelete: "restrict" }),
  posted_at: timestamp("posted_at"),
  posting_watermark: integer("posting_watermark"),
  cancelled_by: text("cancelled_by").references(() => user.id, { onDelete: "restrict" }),
  cancellation_reason: text("cancellation_reason"),
  needs_review_reason: text("needs_review_reason"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
}, (table) => [
  uniqueIndex("stock_counts_branch_number_uidx").on(table.branch_id, table.count_number),
  uniqueIndex("stock_counts_idempotency_uidx").on(table.idempotency_key),
  uniqueIndex("stock_counts_active_location_uidx").on(table.branch_id, table.location_id).where(sql`${table.status} in ('draft', 'counting', 'submitted', 'approved', 'needs_review')`),
  index("stock_counts_branch_status_idx").on(table.branch_id, table.status),
  check("stock_counts_status_check", sql`${table.status} in ('draft', 'counting', 'submitted', 'approved', 'posted', 'cancelled', 'needs_review', 'reversed')`),
]);

export const stockCountLines = pgTable("stock_count_lines", {
  id: serial("id").primaryKey(),
  count_id: integer("count_id").notNull().references(() => stockCounts.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
  ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
  ingredient_sku_snapshot: varchar("ingredient_sku_snapshot", { length: 40 }).notNull(),
  ingredient_name_en_snapshot: varchar("ingredient_name_en_snapshot", { length: 160 }).notNull(),
  ingredient_name_ar_snapshot: varchar("ingredient_name_ar_snapshot", { length: 160 }).notNull(),
  dimension_snapshot: varchar("dimension_snapshot", { length: 16 }).notNull(),
  base_unit_id: integer("base_unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
  base_unit_code_snapshot: varchar("base_unit_code_snapshot", { length: 24 }).notNull(),
  expected_quantity_base: bigint("expected_quantity_base", { mode: "number" }).notNull(),
  expected_unit_cost_micros: bigint("expected_unit_cost_micros", { mode: "number" }).notNull(),
  movement_watermark: integer("movement_watermark").notNull(),
  counted_input_scaled: bigint("counted_input_scaled", { mode: "number" }),
  counted_unit_id: integer("counted_unit_id").references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
  counted_unit_code_snapshot: varchar("counted_unit_code_snapshot", { length: 24 }),
  package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
  package_code_snapshot: varchar("package_code_snapshot", { length: 24 }),
  package_name_en_snapshot: varchar("package_name_en_snapshot", { length: 60 }),
  package_name_ar_snapshot: varchar("package_name_ar_snapshot", { length: 60 }),
  conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
  conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
  counted_quantity_base: bigint("counted_quantity_base", { mode: "number" }),
  zero_confirmed: boolean("zero_confirmed").default(false).notNull(),
  variance_base: bigint("variance_base", { mode: "number" }),
  valuation_unit_cost_micros: bigint("valuation_unit_cost_micros", { mode: "number" }),
  valuation_amount: integer("valuation_amount"),
  posted_balance_quantity: bigint("posted_balance_quantity", { mode: "number" }),
  notes: text("notes"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
}, (table) => [
  uniqueIndex("stock_count_lines_count_ingredient_uidx").on(table.count_id, table.ingredient_id),
  index("stock_count_lines_branch_location_idx").on(table.branch_id, table.location_id),
  check("stock_count_lines_expected_check", sql`${table.expected_quantity_base} >= 0 and ${table.expected_unit_cost_micros} >= 0`),
  check("stock_count_lines_conversion_check", sql`${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`),
  check("stock_count_lines_counted_check", sql`${table.counted_quantity_base} is null or ${table.counted_quantity_base} >= 0`),
  check("stock_count_lines_dimension_check", sql`${table.dimension_snapshot} in ('mass', 'volume', 'count')`),
]);

export const stockCountEntries = pgTable("stock_count_entries", {
  id: serial("id").primaryKey(),
  count_id: integer("count_id").notNull().references(() => stockCounts.id, { onDelete: "restrict" }),
  line_id: integer("line_id").notNull().references(() => stockCountLines.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
  quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
  unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
  unit_code_snapshot: varchar("unit_code_snapshot", { length: 24 }).notNull(),
  package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
  package_code_snapshot: varchar("package_code_snapshot", { length: 24 }),
  conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
  conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
  zero_confirmed: boolean("zero_confirmed").notNull(),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_count_entries_idempotency_uidx").on(table.idempotency_key), index("stock_count_entries_line_idx").on(table.count_id, table.line_id, table.created_at), check("stock_count_entries_values_check", sql`${table.quantity_input_scaled} >= 0 and ${table.quantity_base} >= 0 and ${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`)]);

export const stockCountReversals = pgTable("stock_count_reversals", {
  id: serial("id").primaryKey(),
  count_id: integer("count_id").notNull().references(() => stockCounts.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  status: varchar("status", { length: 16 }).notNull(),
  reason: text("reason").notNull(),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_count_reversals_count_uidx").on(table.count_id), uniqueIndex("stock_count_reversals_idempotency_uidx").on(table.idempotency_key), check("stock_count_reversals_status_check", sql`${table.status} in ('reversed', 'needs_review')`), check("stock_count_reversals_reason_check", sql`length(trim(${table.reason})) >= 3`)]);

export const stockCountStatusHistory = pgTable("stock_count_status_history", {
  id: serial("id").primaryKey(),
  count_id: integer("count_id").notNull().references(() => stockCounts.id, { onDelete: "restrict" }),
  branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
  from_status: varchar("from_status", { length: 20 }),
  to_status: varchar("to_status", { length: 20 }).$type<StockCountStatus>().notNull(),
  actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
  reason: text("reason"),
  idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
}, (table) => [uniqueIndex("stock_count_status_history_idempotency_uidx").on(table.idempotency_key), index("stock_count_status_history_count_idx").on(table.count_id, table.created_at)]);

export const stockBalances = pgTable(
  "stock_balances",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    quantity_base: bigint("quantity_base", { mode: "number" }).default(0).notNull(),
    average_unit_cost_micros: bigint("average_unit_cost_micros", { mode: "number" }).default(0).notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("stock_balances_location_ingredient_uidx").on(table.location_id, table.ingredient_id),
    index("stock_balances_branch_idx").on(table.branch_id),
    check("stock_balances_average_cost_check", sql`${table.average_unit_cost_micros} >= 0`),
  ],
);

export const recipeVersions = pgTable(
  "recipe_versions",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    menu_item_id: integer("menu_item_id").notNull().references(() => menuItems.id, { onDelete: "restrict" }),
    variant_id: integer("variant_id").references(() => menuItemVariants.id, { onDelete: "restrict" }),
    version: integer("version").notNull(),
    status: varchar("status", { length: 12 }).$type<RecipeStatus>().default("draft").notNull(),
    effective_at: timestamp("effective_at"),
    yield_loss_bps: integer("yield_loss_bps").default(0).notNull(),
    authored_by: text("authored_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
    approved_at: timestamp("approved_at"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("recipe_versions_configuration_version_uidx").on(table.menu_item_id, table.variant_id, table.version),
    uniqueIndex("recipe_versions_base_version_uidx").on(table.menu_item_id, table.version).where(sql`${table.variant_id} is null`),
    uniqueIndex("recipe_versions_active_base_uidx").on(table.menu_item_id).where(sql`${table.status} = 'active' and ${table.variant_id} is null`),
    uniqueIndex("recipe_versions_active_variant_uidx").on(table.menu_item_id, table.variant_id).where(sql`${table.status} = 'active' and ${table.variant_id} is not null`),
    index("recipe_versions_branch_status_idx").on(table.branch_id, table.status),
    check("recipe_versions_version_check", sql`${table.version} > 0`),
    check("recipe_versions_status_check", sql`${table.status} in ('draft', 'active', 'retired')`),
    check("recipe_versions_yield_check", sql`${table.yield_loss_bps} >= 0 and ${table.yield_loss_bps} < 10000`),
  ],
);

export const recipeComponents = pgTable(
  "recipe_components",
  {
    id: serial("id").primaryKey(),
    recipe_version_id: integer("recipe_version_id").notNull().references(() => recipeVersions.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    source_location_id: integer("source_location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    modifier_option_id: integer("modifier_option_id").references(() => modifierOptions.id, { onDelete: "restrict" }),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
    quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("recipe_components_unambiguous_uidx").on(table.recipe_version_id, table.ingredient_id, table.source_location_id, table.modifier_option_id),
    uniqueIndex("recipe_components_base_uidx").on(table.recipe_version_id, table.ingredient_id, table.source_location_id).where(sql`${table.modifier_option_id} is null`),
    index("recipe_components_recipe_idx").on(table.recipe_version_id),
    check("recipe_components_quantity_check", sql`${table.quantity_input_scaled} <> 0 and ${table.quantity_base} <> 0`),
  ],
);

export const orderInventoryIssues = pgTable(
  "order_inventory_issues",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    order_id: integer("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }),
    idempotency_key: varchar("idempotency_key", { length: 120 }).notNull(),
    status: varchar("status", { length: 16 }).default("issued").notNull(),
    total_cogs_amount: integer("total_cogs_amount").notNull(),
    issued_by: text("issued_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    issued_at: timestamp("issued_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("order_inventory_issues_order_uidx").on(table.order_id),
    uniqueIndex("order_inventory_issues_idempotency_uidx").on(table.idempotency_key),
    check("order_inventory_issues_status_check", sql`${table.status} in ('issued', 'returned', 'discarded')`),
    check("order_inventory_issues_cost_check", sql`${table.total_cogs_amount} >= 0`),
  ],
);

export const orderInventoryConsumptions = pgTable(
  "order_inventory_consumptions",
  {
    id: serial("id").primaryKey(),
    issue_id: integer("issue_id").notNull().references(() => orderInventoryIssues.id, { onDelete: "restrict" }),
    order_id: integer("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }),
    order_item_id: integer("order_item_id").notNull().references(() => orderItems.id, { onDelete: "restrict" }),
    recipe_version_id: integer("recipe_version_id").notNull().references(() => recipeVersions.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
    unit_cost_micros: bigint("unit_cost_micros", { mode: "number" }).notNull(),
    total_cost_amount: integer("total_cost_amount").notNull(),
  },
  (table) => [
    uniqueIndex("order_inventory_consumptions_snapshot_uidx").on(table.issue_id, table.order_item_id, table.ingredient_id, table.location_id),
    index("order_inventory_consumptions_order_idx").on(table.order_id),
    check("order_inventory_consumptions_values_check", sql`${table.quantity_base} > 0 and ${table.unit_cost_micros} >= 0 and ${table.total_cost_amount} >= 0`),
  ],
);

export const orderItemCogs = pgTable(
  "order_item_cogs",
  {
    id: serial("id").primaryKey(),
    order_id: integer("order_id").notNull().references(() => orders.id, { onDelete: "restrict" }),
    order_item_id: integer("order_item_id").notNull().references(() => orderItems.id, { onDelete: "restrict" }),
    recipe_version_id: integer("recipe_version_id").notNull().references(() => recipeVersions.id, { onDelete: "restrict" }),
    quantity: integer("quantity").notNull(),
    total_cogs_amount: integer("total_cogs_amount").notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("order_item_cogs_item_uidx").on(table.order_item_id),
    check("order_item_cogs_values_check", sql`${table.quantity} > 0 and ${table.total_cogs_amount} >= 0`),
  ],
);

export const stockMovements = pgTable(
  "stock_movements",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    movement_type: varchar("movement_type", { length: 32 }).$type<StockMovementType>().notNull(),
    direction: integer("direction").notNull(),
    quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
    unit_cost_micros: bigint("unit_cost_micros", { mode: "number" }).notNull(),
    total_cost_amount: integer("total_cost_amount").notNull(),
    source_type: varchar("source_type", { length: 40 }).notNull(),
    source_id: varchar("source_id", { length: 100 }).notNull(),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    reason: text("reason"),
    order_id: integer("order_id").references(() => orders.id, { onDelete: "restrict" }),
    order_item_id: integer("order_item_id").references(() => orderItems.id, { onDelete: "restrict" }),
    recipe_version_id: integer("recipe_version_id").references(() => recipeVersions.id, { onDelete: "restrict" }),
    supplier_return_id: integer("supplier_return_id").references(() => supplierReturns.id, { onDelete: "restrict" }),
    supplier_return_line_id: integer("supplier_return_line_id").references(() => supplierReturnLines.id, { onDelete: "restrict" }),
    purchase_receipt_id: integer("purchase_receipt_id").references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    purchase_receipt_line_id: integer("purchase_receipt_line_id").references(() => purchaseReceiptLines.id, { onDelete: "restrict" }),
    stock_transfer_id: integer("stock_transfer_id").references(() => stockTransfers.id, { onDelete: "restrict" }),
    stock_transfer_line_id: integer("stock_transfer_line_id").references(() => stockTransferLines.id, { onDelete: "restrict" }),
    stock_transfer_dispatch_id: integer("stock_transfer_dispatch_id").references(() => stockTransferDispatches.id, { onDelete: "restrict" }),
    stock_transfer_dispatch_line_id: integer("stock_transfer_dispatch_line_id").references(() => stockTransferDispatchLines.id, { onDelete: "restrict" }),
    stock_transfer_receipt_id: integer("stock_transfer_receipt_id").references(() => stockTransferReceipts.id, { onDelete: "restrict" }),
    stock_transfer_receipt_line_id: integer("stock_transfer_receipt_line_id").references(() => stockTransferReceiptLines.id, { onDelete: "restrict" }),
    stock_transfer_reversal_id: integer("stock_transfer_reversal_id").references(() => stockTransferReversals.id, { onDelete: "restrict" }),
    stock_count_id: integer("stock_count_id").references(() => stockCounts.id, { onDelete: "restrict" }),
    stock_count_line_id: integer("stock_count_line_id").references(() => stockCountLines.id, { onDelete: "restrict" }),
    stock_count_reversal_id: integer("stock_count_reversal_id").references(() => stockCountReversals.id, { onDelete: "restrict" }),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("stock_movements_idempotency_uidx").on(table.idempotency_key),
    index("stock_movements_ingredient_created_idx").on(table.ingredient_id, table.created_at),
    index("stock_movements_order_idx").on(table.order_id),
    check("stock_movements_type_check", sql`${table.movement_type} in ('opening_balance', 'manual_positive', 'manual_negative', 'sale_consumption', 'sale_consumption_reversal', 'waste_discard', 'negative_override', 'purchase_receipt', 'purchase_receipt_reversal', 'supplier_return', 'supplier_return_reversal', 'stock_transfer_out', 'stock_transfer_in', 'stock_transfer_reversal_out', 'stock_transfer_reversal_in', 'stock_count_positive', 'stock_count_negative', 'stock_count_reversal_positive', 'stock_count_reversal_negative')`),
    check("stock_movements_values_check", sql`${table.direction} in (-1, 0, 1) and ${table.quantity_base} > 0 and ${table.unit_cost_micros} >= 0 and ${table.total_cost_amount} >= 0`),
  ],
);
