import {
  bigint,
  boolean,
  check,
  index,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
  varchar,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type {
  PurchaseOrderStatus,
  PurchaseOrderReceivingStatus,
  PurchaseReceiptStatus,
  SupplierReturnStatus,
  SupplierReturnReason,
} from "./constants";
import { branches } from "./restaurant";
import {
  inventoryLocations,
  ingredients,
  ingredientPackageConversions,
  unitsOfMeasure,
} from "./inventory";
import { user } from "../auth-schema";

export const suppliers = pgTable(
  "suppliers",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    code: varchar("code", { length: 40 }).notNull(),
    name_en: varchar("name_en", { length: 160 }).notNull(),
    name_ar: varchar("name_ar", { length: 160 }).notNull(),
    contact_name: varchar("contact_name", { length: 120 }),
    phone: varchar("phone", { length: 32 }),
    email: varchar("email", { length: 160 }),
    address: text("address"),
    notes: text("notes"),
    is_active: boolean("is_active").default(true).notNull(),
    created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    updated_by: text("updated_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("suppliers_branch_code_uidx").on(table.branch_id, table.code),
    index("suppliers_branch_active_idx").on(table.branch_id, table.is_active),
  ],
);

export const purchaseOrders = pgTable(
  "purchase_orders",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    supplier_id: integer("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }),
    supplier_code_snapshot: varchar("supplier_code_snapshot", { length: 40 }).notNull(),
    supplier_name_en_snapshot: varchar("supplier_name_en_snapshot", { length: 160 }).notNull(),
    supplier_name_ar_snapshot: varchar("supplier_name_ar_snapshot", { length: 160 }).notNull(),
    po_number: varchar("po_number", { length: 48 }).notNull(),
      status: varchar("status", { length: 20 }).$type<PurchaseOrderStatus>().default("draft").notNull(),
      receiving_status: varchar("receiving_status", { length: 24 }).$type<PurchaseOrderReceivingStatus>().default("not_received").notNull(),
    order_date: timestamp("order_date").defaultNow().notNull(),
    expected_date: timestamp("expected_date"),
    currency: varchar("currency", { length: 3 }).default("EGP").notNull(),
    subtotal_amount: integer("subtotal_amount").default(0).notNull(),
    total_amount: integer("total_amount").default(0).notNull(),
    notes: text("notes"),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    submitted_by: text("submitted_by").references(() => user.id, { onDelete: "restrict" }),
    approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
    cancelled_by: text("cancelled_by").references(() => user.id, { onDelete: "restrict" }),
    cancellation_reason: text("cancellation_reason"),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_orders_branch_number_uidx").on(table.branch_id, table.po_number),
    uniqueIndex("purchase_orders_idempotency_uidx").on(table.idempotency_key),
    index("purchase_orders_branch_status_created_idx").on(table.branch_id, table.status, table.created_at),
      check("purchase_orders_status_check", sql`${table.status} in ('draft', 'submitted', 'approved', 'cancelled')`),
      check("purchase_orders_receiving_status_check", sql`${table.receiving_status} in ('not_received', 'partially_received', 'fully_received')`),
    check("purchase_orders_amounts_check", sql`${table.subtotal_amount} >= 0 and ${table.total_amount} = ${table.subtotal_amount} and ${table.subtotal_amount} <= 2147483647`),
  ],
);

export const purchaseOrderLines = pgTable(
  "purchase_order_lines",
  {
    id: serial("id").primaryKey(),
    purchase_order_id: integer("purchase_order_id").notNull().references(() => purchaseOrders.id, { onDelete: "cascade" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    ingredient_sku: varchar("ingredient_sku", { length: 40 }).notNull(),
    ingredient_name_en: varchar("ingredient_name_en", { length: 160 }).notNull(),
    ingredient_name_ar: varchar("ingredient_name_ar", { length: 160 }).notNull(),
    unit_code: varchar("unit_code", { length: 24 }).notNull(),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
      quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
      conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }),
      conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }),
    unit_price_minor: integer("unit_price_minor").notNull(),
    line_total_amount: integer("line_total_amount").notNull(),
    notes: text("notes"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    index("purchase_order_lines_order_idx").on(table.purchase_order_id),
    index("purchase_order_lines_ingredient_idx").on(table.ingredient_id),
      check("purchase_order_lines_values_check", sql`${table.quantity_input_scaled} > 0 and ${table.quantity_base} > 0 and ${table.unit_price_minor} >= 0 and ${table.line_total_amount} >= 0 and ${table.line_total_amount} <= 2147483647`),
      check("purchase_order_lines_conversion_snapshot_check", sql`(${table.conversion_numerator_snapshot} is null and ${table.conversion_denominator_snapshot} is null) or (${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0)`),
    ],
  );

export const purchaseReceipts = pgTable(
  "purchase_receipts",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    purchase_order_id: integer("purchase_order_id").notNull().references(() => purchaseOrders.id, { onDelete: "restrict" }),
    supplier_id: integer("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }),
    supplier_code_snapshot: varchar("supplier_code_snapshot", { length: 40 }).notNull(),
    supplier_name_en_snapshot: varchar("supplier_name_en_snapshot", { length: 160 }).notNull(),
    supplier_name_ar_snapshot: varchar("supplier_name_ar_snapshot", { length: 160 }).notNull(),
    po_number_snapshot: varchar("po_number_snapshot", { length: 48 }).notNull(),
    receipt_number: varchar("receipt_number", { length: 48 }).notNull(),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    supplier_delivery_note: varchar("supplier_delivery_note", { length: 120 }),
    supplier_invoice_reference: varchar("supplier_invoice_reference", { length: 120 }),
    received_at: timestamp("received_at").defaultNow().notNull(),
    received_by: text("received_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    notes: text("notes"),
    status: varchar("status", { length: 20 }).$type<PurchaseReceiptStatus>().default("draft").notNull(),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    posted_at: timestamp("posted_at"),
    posted_by: text("posted_by").references(() => user.id, { onDelete: "restrict" }),
    variance_approved_by: text("variance_approved_by").references(() => user.id, { onDelete: "restrict" }),
    variance_reason: text("variance_reason"),
    overreceive_approved_by: text("overreceive_approved_by").references(() => user.id, { onDelete: "restrict" }),
    overreceive_reason: text("overreceive_reason"),
    reversal_reason: text("reversal_reason"),
    needs_review_reason: text("needs_review_reason"),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_receipts_branch_number_uidx").on(table.branch_id, table.receipt_number),
    uniqueIndex("purchase_receipts_idempotency_uidx").on(table.idempotency_key),
    index("purchase_receipts_branch_status_created_idx").on(table.branch_id, table.status, table.created_at),
    index("purchase_receipts_po_idx").on(table.purchase_order_id, table.created_at),
    check("purchase_receipts_status_check", sql`${table.status} in ('draft', 'posted', 'reversed', 'needs_review')`),
    check("purchase_receipts_reversal_reason_check", sql`${table.status} not in ('reversed', 'needs_review') or length(trim(coalesce(${table.reversal_reason}, ${table.needs_review_reason}, ''))) > 0`),
  ],
);

export const purchaseReceiptLines = pgTable(
  "purchase_receipt_lines",
  {
    id: serial("id").primaryKey(),
    receipt_id: integer("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    purchase_order_line_id: integer("purchase_order_line_id").notNull().references(() => purchaseOrderLines.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    ingredient_sku_snapshot: varchar("ingredient_sku_snapshot", { length: 40 }).notNull(),
    ingredient_name_en_snapshot: varchar("ingredient_name_en_snapshot", { length: 160 }).notNull(),
    ingredient_name_ar_snapshot: varchar("ingredient_name_ar_snapshot", { length: 160 }).notNull(),
    package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    unit_code_snapshot: varchar("unit_code_snapshot", { length: 24 }).notNull(),
    conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
    conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
    ordered_quantity_base_snapshot: bigint("ordered_quantity_base_snapshot", { mode: "number" }).notNull(),
    po_unit_price_minor_snapshot: integer("po_unit_price_minor_snapshot").notNull(),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
    accepted_quantity_base: bigint("accepted_quantity_base", { mode: "number" }).notNull(),
    rejected_quantity_base: bigint("rejected_quantity_base", { mode: "number" }).notNull(),
    damaged_quantity_base: bigint("damaged_quantity_base", { mode: "number" }).notNull(),
    actual_unit_price_minor: integer("actual_unit_price_minor").notNull(),
    accepted_unit_cost_micros_snapshot: bigint("accepted_unit_cost_micros_snapshot", { mode: "number" }).notNull(),
    balance_quantity_before: bigint("balance_quantity_before", { mode: "number" }),
    balance_unit_cost_before: bigint("balance_unit_cost_before", { mode: "number" }),
    ingredient_average_unit_cost_before: bigint("ingredient_average_unit_cost_before", { mode: "number" }),
    line_total_amount: integer("line_total_amount").notNull(),
    notes: text("notes"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_receipt_lines_receipt_po_line_uidx").on(table.receipt_id, table.purchase_order_line_id),
    index("purchase_receipt_lines_po_line_idx").on(table.purchase_order_line_id),
    check("purchase_receipt_lines_conversion_check", sql`${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`),
    check("purchase_receipt_lines_values_check", sql`${table.quantity_input_scaled} > 0 and ${table.accepted_quantity_base} >= 0 and ${table.rejected_quantity_base} >= 0 and ${table.damaged_quantity_base} >= 0 and ${table.actual_unit_price_minor} >= 0 and ${table.po_unit_price_minor_snapshot} >= 0 and ${table.accepted_unit_cost_micros_snapshot} >= 0 and ${table.line_total_amount} >= 0 and ${table.line_total_amount} <= 2147483647`),
  ],
);

export const purchaseReceiptReversals = pgTable(
  "purchase_receipt_reversals",
  {
    id: serial("id").primaryKey(),
    receipt_id: integer("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    reason: text("reason").notNull(),
    status: varchar("status", { length: 16 }).notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("purchase_receipt_reversals_receipt_uidx").on(table.receipt_id),
    uniqueIndex("purchase_receipt_reversals_idempotency_uidx").on(table.idempotency_key),
    check("purchase_receipt_reversals_reason_check", sql`length(trim(${table.reason})) >= 3`),
    check("purchase_receipt_reversals_status_check", sql`${table.status} in ('reversed', 'needs_review')`),
  ],
);

export const supplierReturns = pgTable(
  "supplier_returns",
  {
    id: serial("id").primaryKey(),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    supplier_id: integer("supplier_id").notNull().references(() => suppliers.id, { onDelete: "restrict" }),
    purchase_order_id: integer("purchase_order_id").notNull().references(() => purchaseOrders.id, { onDelete: "restrict" }),
    receipt_id: integer("receipt_id").notNull().references(() => purchaseReceipts.id, { onDelete: "restrict" }),
    location_id: integer("location_id").notNull().references(() => inventoryLocations.id, { onDelete: "restrict" }),
    return_number: varchar("return_number", { length: 48 }).notNull(),
    supplier_code_snapshot: varchar("supplier_code_snapshot", { length: 40 }).notNull(),
    supplier_name_en_snapshot: varchar("supplier_name_en_snapshot", { length: 160 }).notNull(),
    supplier_name_ar_snapshot: varchar("supplier_name_ar_snapshot", { length: 160 }).notNull(),
    po_number_snapshot: varchar("po_number_snapshot", { length: 48 }).notNull(),
    receipt_number_snapshot: varchar("receipt_number_snapshot", { length: 48 }).notNull(),
    reason_code: varchar("reason_code", { length: 24 }).$type<SupplierReturnReason>().notNull(),
    reason: text("reason"),
    notes: text("notes"),
    evidence_metadata: text("evidence_metadata"),
    status: varchar("status", { length: 20 }).$type<SupplierReturnStatus>().default("draft").notNull(),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    expected_credit_amount: integer("expected_credit_amount").default(0).notNull(),
    valuation_amount: integer("valuation_amount"),
    cost_variance_amount: integer("cost_variance_amount"),
    created_by: text("created_by").notNull().references(() => user.id, { onDelete: "restrict" }),
    submitted_by: text("submitted_by").references(() => user.id, { onDelete: "restrict" }),
    approved_by: text("approved_by").references(() => user.id, { onDelete: "restrict" }),
    dispatched_by: text("dispatched_by").references(() => user.id, { onDelete: "restrict" }),
    cancelled_by: text("cancelled_by").references(() => user.id, { onDelete: "restrict" }),
    reversed_by: text("reversed_by").references(() => user.id, { onDelete: "restrict" }),
    submitted_at: timestamp("submitted_at"),
    approved_at: timestamp("approved_at"),
    dispatched_at: timestamp("dispatched_at"),
    cancelled_at: timestamp("cancelled_at"),
    reversed_at: timestamp("reversed_at"),
    cancellation_reason: text("cancellation_reason"),
    needs_review_reason: text("needs_review_reason"),
    created_at: timestamp("created_at").defaultNow().notNull(),
    updated_at: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_returns_branch_number_uidx").on(table.branch_id, table.return_number),
    uniqueIndex("supplier_returns_idempotency_uidx").on(table.idempotency_key),
    index("supplier_returns_branch_status_created_idx").on(table.branch_id, table.status, table.created_at),
    index("supplier_returns_receipt_idx").on(table.receipt_id, table.created_at),
    check("supplier_returns_status_check", sql`${table.status} in ('draft', 'submitted', 'approved', 'dispatched', 'cancelled', 'needs_review', 'reversed')`),
    check("supplier_returns_reason_check", sql`${table.reason_code} in ('damaged', 'expired', 'wrong_item', 'quality_issue', 'over_delivery', 'other')`),
    check("supplier_returns_money_check", sql`${table.expected_credit_amount} >= 0 and (${table.valuation_amount} is null or ${table.valuation_amount} >= 0) and (${table.cost_variance_amount} is null or ${table.cost_variance_amount} between -2147483647 and 2147483647)`),
    check("supplier_returns_review_reason_check", sql`${table.status} <> 'needs_review' or length(trim(coalesce(${table.needs_review_reason}, ''))) > 0`),
  ],
);

export const supplierReturnLines = pgTable(
  "supplier_return_lines",
  {
    id: serial("id").primaryKey(),
    supplier_return_id: integer("supplier_return_id").notNull().references(() => supplierReturns.id, { onDelete: "restrict" }),
    receipt_line_id: integer("receipt_line_id").notNull().references(() => purchaseReceiptLines.id, { onDelete: "restrict" }),
    ingredient_id: integer("ingredient_id").notNull().references(() => ingredients.id, { onDelete: "restrict" }),
    ingredient_sku_snapshot: varchar("ingredient_sku_snapshot", { length: 40 }).notNull(),
    ingredient_name_en_snapshot: varchar("ingredient_name_en_snapshot", { length: 160 }).notNull(),
    ingredient_name_ar_snapshot: varchar("ingredient_name_ar_snapshot", { length: 160 }).notNull(),
    dimension_snapshot: varchar("dimension_snapshot", { length: 16 }).notNull(),
    unit_id: integer("unit_id").notNull().references(() => unitsOfMeasure.id, { onDelete: "restrict" }),
    unit_code_snapshot: varchar("unit_code_snapshot", { length: 24 }).notNull(),
    package_conversion_id: integer("package_conversion_id").references(() => ingredientPackageConversions.id, { onDelete: "restrict" }),
    conversion_numerator_snapshot: bigint("conversion_numerator_snapshot", { mode: "number" }).notNull(),
    conversion_denominator_snapshot: bigint("conversion_denominator_snapshot", { mode: "number" }).notNull(),
    quantity_input_scaled: bigint("quantity_input_scaled", { mode: "number" }).notNull(),
    quantity_base: bigint("quantity_base", { mode: "number" }).notNull(),
    accepted_quantity_base_snapshot: bigint("accepted_quantity_base_snapshot", { mode: "number" }).notNull(),
    original_unit_cost_micros_snapshot: bigint("original_unit_cost_micros_snapshot", { mode: "number" }).notNull(),
    expected_credit_amount: integer("expected_credit_amount").notNull(),
    dispatch_unit_cost_micros_snapshot: bigint("dispatch_unit_cost_micros_snapshot", { mode: "number" }),
    dispatch_valuation_amount: integer("dispatch_valuation_amount"),
    notes: text("notes"),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_return_lines_return_receipt_line_uidx").on(table.supplier_return_id, table.receipt_line_id),
    index("supplier_return_lines_receipt_line_idx").on(table.receipt_line_id),
    check("supplier_return_lines_conversion_check", sql`${table.conversion_numerator_snapshot} > 0 and ${table.conversion_denominator_snapshot} > 0`),
    check("supplier_return_lines_dimension_check", sql`${table.dimension_snapshot} in ('mass', 'volume', 'count')`),
    check("supplier_return_lines_quantities_check", sql`${table.quantity_input_scaled} > 0 and ${table.quantity_base} > 0 and ${table.accepted_quantity_base_snapshot} >= ${table.quantity_base}`),
    check("supplier_return_lines_cost_check", sql`${table.original_unit_cost_micros_snapshot} >= 0 and ${table.expected_credit_amount} >= 0 and (${table.dispatch_unit_cost_micros_snapshot} is null or ${table.dispatch_unit_cost_micros_snapshot} >= 0) and (${table.dispatch_valuation_amount} is null or ${table.dispatch_valuation_amount} >= 0)`),
  ],
);

export const supplierReturnStatusHistory = pgTable(
  "supplier_return_status_history",
  {
    id: serial("id").primaryKey(),
    supplier_return_id: integer("supplier_return_id").notNull().references(() => supplierReturns.id, { onDelete: "restrict" }),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    from_status: varchar("from_status", { length: 20 }),
    to_status: varchar("to_status", { length: 20 }).$type<SupplierReturnStatus>().notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    reason: text("reason"),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_return_status_history_idempotency_uidx").on(table.idempotency_key),
    index("supplier_return_status_history_return_idx").on(table.supplier_return_id, table.created_at),
  ],
);

export const supplierReturnReversals = pgTable(
  "supplier_return_reversals",
  {
    id: serial("id").primaryKey(),
    supplier_return_id: integer("supplier_return_id").notNull().references(() => supplierReturns.id, { onDelete: "restrict" }),
    branch_id: integer("branch_id").notNull().references(() => branches.id, { onDelete: "restrict" }),
    reason: text("reason").notNull(),
    status: varchar("status", { length: 16 }).notNull(),
    actor_user_id: text("actor_user_id").notNull().references(() => user.id, { onDelete: "restrict" }),
    idempotency_key: varchar("idempotency_key", { length: 140 }).notNull(),
    created_at: timestamp("created_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("supplier_return_reversals_return_uidx").on(table.supplier_return_id),
    uniqueIndex("supplier_return_reversals_idempotency_uidx").on(table.idempotency_key),
    check("supplier_return_reversals_reason_check", sql`length(trim(${table.reason})) >= 3`),
    check("supplier_return_reversals_status_check", sql`${table.status} in ('reversed', 'needs_review')`),
  ],
);
